[package]
name = "orbbec-sdk-sys"
version = "0.3.3+2.10.6"
edition = "2024"
authors = ["Rao Zvorovski"]
keywords = ["orbbec", "gemini", "astra", "femto", 'rgbd']
categories = ["external-ffi-bindings", "computer-vision"]
links = "orbbec-sdk-2"
description = "Low-level Rust bindings for https://github.com/orbbec/OrbbecSDK_v2"
license = "MIT"
repository = "https://github.com/raoz/orbbec-sdk-sys"
exclude = [
    "vendor/docs",
    "vendor/examples",
    "vendor/tests",
    "vendor/3rdparty/libjpeg/src/testimages",
    "vendor/3rdparty/libjpeg/src/doc",
    "vendor/3rdparty/libjpeg/src/java",
    "vendor/3rdparty/libyuv/src/unit_test",
    "vendor/3rdparty/libyuv/src/docs",
    "vendor/3rdparty/live555/src/testProgs",
    "vendor/3rdparty/jsoncpp/src/test",
    "vendor/3rdparty/jsoncpp/src/doc",
    "vendor/3rdparty/jsoncpp/src/example",
    "vendor/3rdparty/libusb/src/examples",
    "vendor/3rdparty/libusb/src/doc",
    "vendor/3rdparty/libusb/src/tests",
]

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1"
fs_extra = "1.3.0"

[features]
cmake-min-3-5 = []